-- AlterTable
ALTER TABLE "PickGame" ADD COLUMN     "lpChangeTeamBlue" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "lpChangeTeamRed" DOUBLE PRECISION NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "Player" ALTER COLUMN "lpPick" SET DEFAULT 1350;
